llvm 3.3-1 i686 by SirAnthony

diff --git a/llvm/ABUILD b/llvm/ABUILD
--- a/llvm/ABUILD
+++ b/llvm/ABUILD
@@ -1,64 +1,51 @@
 # ABUILD generated by mkpkg_generator.sh
 
 pkgname=llvm
-pkgver=2.9
-pkgbuild=2
+pkgver=3.3
+pkgbuild=1
 arch=("auto")
-_gcc_ver=4.5.2
+_gcc_ver=4.7.3
 shortdesc="Low Level Virtual Machine"
 
 tags=("develop sys-devel")
 
-source=("http://llvm.org/releases/$pkgver/$pkgname-$pkgver.tgz"
-        "http://llvm.org/releases/$pkgver/clang-$pkgver.tgz")
+source=("http://llvm.org/releases/$pkgver/llvm-$pkgver.src.tar.gz"
+	"http://llvm.org/releases/$pkgver/cfe-$pkgver.src.tar.gz"
+	"http://llvm.org/releases/$pkgver/compiler-rt-$pkgver.src.tar.gz")
 
-
-
-BUILD_SYSTEM="autotools"
-BUILD_KEYS="--prefix=/usr --libdir=/usr/lib$LIBDIRSUFFIX --mandir=/usr/man --sysconfdir=/etc"
-INSTALL_KEYS="DESTDIR=$pkgdir"
-
+build_deps="libffi python ocaml python-sphinx"
 pkglist="clang llvm_ocaml clang_analyzer"
 adddep="perl"
+
 build() {
-	cd "$srcdir/$pkgname-$pkgver"
+	cd "$srcdir/$pkgname-$pkgver.src"
 
 	# At the present, clang must reside inside the LLVM source code tree to build
-	# See http://llvm.org/bugs/show_bug.cgi?id=4840
-	rm -rf tools/clang
-	cp -r "$srcdir/clang-$pkgver" tools/clang
+	# See http://llvm.org/bugs/show_bug.cgi?id=4840	
+	mv "$srcdir/cfe-$pkgver.src" tools/clang
+	mv "$srcdir/compiler-rt-$pkgver.src" projects/compiler-rt
 
-	# Fix symbolic links from OCaml bindings to LLVM libraries
-	sed -i 's:\$(PROJ_libdir):/usr/lib'${LIBDIRSUFFIX}'/llvm:' bindings/ocaml/Makefile.ocaml
+	# unfortunately ./configure won't listen to --mandir and the-like, so take
+	# care of this.
+	sed -e 's,^PROJ_docsdir.*,PROJ_docsdir := $(PROJ_prefix)/doc/'${pkgname}-${pkgver}, \
+	    -e 's,^PROJ_mandir.*,PROJ_mandir := $(PROJ_prefix)/man/', \
+	    -e 's,^PROJ_etcdir.*,PROJ_etcdir := /etc/llvm,' \
+	    -e 's,^PROJ_libdir.*,PROJ_libdir := $(PROJ_prefix)/'lib${LIBDIRSUFFIX}/${pkgname}, \
+	    -i Makefile.config.in || die "Makefile.config sed failed"
+	
+	sed -e "/ActiveLibDir = ActivePrefix/s/lib/lib${LIBDIRSUFFIX}\/${pkgname}/" \
+	    -i tools/llvm-config/llvm-config.cpp || die "llvm-config sed failed"
+	
+	# Fixing rpath and CFLAGS
+	sed -e 's,\$(RPATH) -Wl\,\$(\(ToolDir\|LibDir\)),$(RPATH) -Wl\,'/usr/lib${LIBDIRSUFFIX}/${pkgname}, \
+	    -e '/OmitFramePointer/s/-fomit-frame-pointer//' \
+	    -i Makefile.rules || die "rpath sed failed"
+	
 
-	# Fix installation directories, ./configure doesn't seem to set them right
-	sed -i -e 's:\$(PROJ_prefix)/etc/llvm:/etc/llvm:' \
-		-e 's:\$(PROJ_prefix)/lib:$(PROJ_prefix)/lib'${LIBDIRSUFFIX}'/llvm:' \
-		-e 's:\$(PROJ_prefix)/docs/llvm:$(PROJ_prefix)/share/doc/llvm:' \
-	Makefile.config.in
+	sed -e "/NO_INSTALL = 1/s/^/#/" -i utils/FileCheck/Makefile \
+	    || die "FileCheck Makefile sed failed"
 
-	# Fix insecure rpath (http://bugs.archlinux.org/task/14017)
-	sed -i 's:$(RPATH) -Wl,$(\(ToolDir\|LibDir\|ExmplDir\))::g' Makefile.rules
-
-	# Get the correct list of symbols to export
-	# See http://lists.cs.uiuc.edu/pipermail/cfe-dev/2010-April/008559.html
-	patch -Np1 -i "$filedir/clang-plugin-loader-registry.patch"
-
-	# Fix clang path in CIndexer.cpp (https://bugs.archlinux.org/task/22799)
-	patch -d tools/clang -Np0 -i "$filedir/cindexer-clang-path.patch"
-
-	# Add GCC 4.6.1 to GccVersions (FS#23631)
-	patch -d tools/clang -Np1 -i "$filedir/clang-toolchains-gcc-versions.patch"
-
-	# Make -flto work
-	# Use gold instead of default linker, and always use the plugin
-	# Uncomment this if ld.gold is in system
-	# patch -d tools/clang -Np0 -i "$srcdir/enable-lto.patch"
-
-	# Fix upstream bug #9869:
-	#   Operator.h incompatibility with GCC 4.6 in C++0x mode
-	#   Uncomment it when build with gcc 4.6
-	# patch -Np2 -i "$srcdir/bug-9869-operator-h-c++0x.patch"
+	cat ${filedir}/${pkgname}-3.2-nodoctargz.patch | patch -p0
 
 	# Include location of libffi headers in CPPFLAGS
 	export CPPFLAGS="$SLKCXXFLAGS $SLKCPPFLAGS $(pkg-config --cflags libffi)"
@@ -77,53 +64,83 @@ build() {
 
 	# Fix clang headers path
 	sed -e "/PROJ_headers/s#lib/clang#lib${LIBDIRSUFFIX}/clang#" \
-		-i $srcdir/llvm-$pkgver/tools/clang/lib/Headers/Makefile
+		-i $srcdir/llvm-$pkgver.src/tools/clang/lib/Headers/Makefile
 
 	./configure \
 		--prefix=/usr \
 		--libdir=/usr/lib${LIBDIRSUFFIX}/llvm \
 		--sysconfdir=/etc \
+		--mandir=/usr/man \
 		--enable-shared \
 		--enable-libffi \
 		--enable-targets=all \
+		--enable-experimental-targets=R600 \
 		--disable-expensive-checks \
 		--disable-debug-runtime \
 		--disable-assertions \
 		--with-cxx-include-root=$_cxx_headers \
 		--with-cxx-include-arch=$CHOST \
 		--enable-optimized
+		# --with-binutils-include=/usr/include \ # gold plugin
+	
 
 	make REQUIRES_RTTI=1 -j${numjobs}
+	
+	make -j${numjobs} -C docs -f Makefile.sphinx man
+	make -j${numjobs} -C docs -f Makefile.sphinx html
+	make -j${numjobs} -C tools/clang/docs -f Makefile.sphinx html
+}
+
+
+after_build() {
+
+	cd "$srcdir/llvm-$pkgver.src"
 
        	# We move the clang directory out of the tree so it won't get installed and
 	# then we bring it back in for the clang package
 	mv tools/clang "$srcdir"
+
 	# -j1 is due to race conditions during the installation of the OCaml bindings
 	make -j1 DESTDIR="$pkgdir" install
 	mv "$srcdir/clang" tools
 
 	# OCaml bindings go to a separate package
 	rm -rf "$srcdir"/{ocaml,ocamldoc}
-	mv "$pkgdir"/usr/{lib${LIBDIRSUFFIX}/ocaml,share/doc/llvm/ocamldoc} "$srcdir"
+	mv "$pkgdir"/usr/{lib${LIBDIRSUFFIX}/ocaml,doc/llvm-${pkgver}/ocamldoc} "$srcdir"
 
 	# Remove duplicate files installed by the OCaml bindings
-	rm "$pkgdir"/usr/{lib${LIBDIRSUFFIX}/llvm/libllvm*,share/doc/llvm/ocamldoc.tar.gz}
+	#rm "$pkgdir"/usr/{lib${LIBDIRSUFFIX}/llvm/libllvm*,doc/llvm-${pkgver}/ocamldoc.tar.gz}
 
 	# Fix permissions of static libs
 	chmod -x "$pkgdir"/usr/lib${LIBDIRSUFFIX}/llvm/*.a
 
-	# Fix libdir in llvm-config (http://bugs.archlinux.org/task/14487)
-	sed -i 's:\(ABS_RUN_DIR/lib\):\1/llvm:' "$pkgdir/usr/bin/llvm-config"
-
 	# Get rid of example Hello transformation
 	rm "$pkgdir"/usr/lib${LIBDIRSUFFIX}/llvm/*LLVMHello.*
 
-	# Symlink the gold plugin where clang expects it
-	ln -s llvm/LLVMgold.so "$pkgdir/usr/lib${LIBDIRSUFFIX}/LLVMgold.so"
+	# Symlink LLVMgold.so into /usr/lib${LIBDIRSUFFIX}/bfd-plugins
+	# (https://bugs.archlinux.org/task/28479)
+	#install -d "$pkgdir/usr/lib${LIBDIRSUFFIX}/bfd-plugins"
+	#ln -s ../LLVMgold.so "$pkgdir/usr/lib${LIBDIRSUFFIX}/bfd-plugins/LLVMgold.so"
 
-	# Add ld.so.conf.d entry
-	install -d "$pkgdir/etc/ld.so.conf.d"
-	echo /usr/lib${LIBDIRSUFFIX}/llvm >"$pkgdir/etc/ld.so.conf.d/llvm.conf"
+	if [[ $ARCH == x86_64 ]]; then
+	    # Needed for multilib (https://bugs.archlinux.org/task/29951)
+	    # Header stubs are taken from Fedora
+	    for _header in config llvm-config; do
+		mv "$pkgdir/usr/include/llvm/Config/$_header"{,-64}.h
+		cp "$srcdir/llvm-Config-$_header.h" \
+		"$pkgdir/usr/include/llvm/Config/$_header.h"
+	    done
+	fi
+
+	# Install man pages
+	install -d "$pkgdir/usr/man/man1"
+	cp docs/_build/man/*.1 "$pkgdir/usr/man/man1/"
+
+	# Install html docs
+	cp -r docs/_build/html/* "$pkgdir/usr/doc/$pkgname-${pkgver}/html/"
+	rm -r "$pkgdir/usr/doc/$pkgname-${pkgver}/html/_sources"
+
+	install -Dm644 LICENSE.TXT "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
 }
 
 llvm_ocaml() {
@@ -133,14 +150,23 @@ llvm_ocaml() {
 }
 
 llvm_ocaml_prep() {
-	cd "$srcdir/llvm-$pkgver"
+	cd "$srcdir/llvm-$pkgver.src"
 
-	install -d "$pkgdir"/{usr/lib${LIBDIRSUFFIX},usr/share/doc/llvm}
+	install -d "$pkgdir"/{usr/lib${LIBDIRSUFFIX},usr/doc/llvm-${pkgver}}
 	cp -r "$srcdir/ocaml" "$pkgdir/usr/lib${LIBDIRSUFFIX}"
-	cp -r "$srcdir/ocamldoc" "$pkgdir/usr/share/doc/llvm"
+	cp -r "$srcdir/ocamldoc" "$pkgdir/usr/doc/llvm-${pkgver}"
+	
+	( cd "$pkgdir"/usr/lib${LIBDIRSUFFIX}/ocaml/
+	  for file in libllvm*.a; do
+	    rm -f ${file}
+	    ln -s /usr/lib/llvm/${file} ${file}
+	  done
+	)
 
 	# Remove execute bit from static libraries
-	chmod -x "$pkgdir"/usr/lib${LIBDIRSUFFIX}/ocaml/libllvm*.a
+	#chmod -x "$pkgdir"/usr/lib${LIBDIRSUFFIX}/ocaml/libllvm*.a
+
+	install -Dm644 LICENSE.TXT "$pkgdir/usr/share/licenses/llvm-ocaml/LICENSE"
 }
 
 clang() {
@@ -150,24 +176,29 @@ clang() {
 }
 
 clang_prep() {
-	# It looks like clang still needs GCC to assemble and link object files
-	# See http://old.nabble.com/%22clang--v%22-shows-a-GCC-call-td28378453.html
-
 	# Fix installation path for clang docs
-	sed -i 's:$(PROJ_prefix)/share/doc/llvm:$(PROJ_prefix)/share/doc/clang:' \
-		"$srcdir/llvm-$pkgver/Makefile.config"
+	#sed -i 's:$(PROJ_prefix)/doc/llvm-${pkgver}:$(PROJ_prefix)/doc/clang-${pkgver}:' \
+	#   "$srcdir/llvm-$pkgver.src/Makefile.config" 
 
-
-	cd "$srcdir/llvm-$pkgver/tools/clang"
+	cd "$srcdir/llvm-$pkgver.src/tools/clang"
 	make DESTDIR="$pkgdir" install
 
 	# Fix permissions of static libs
 	chmod -x "$pkgdir"/usr/lib${LIBDIRSUFFIX}/llvm/*.a
 
 	# Revert the path change in case we want to do a repackage later
-	sed -i 's:$(PROJ_prefix)/share/doc/clang:$(PROJ_prefix)/share/doc/llvm:' \
-	"$srcdir/llvm-$pkgver/Makefile.config"
+	#sed -i 's:$(PROJ_prefix)/doc/clang-${pkgver}:$(PROJ_prefix)/doc/llvm-${pkgver}:' \
+	#    "$srcdir/llvm-$pkgver.src/Makefile.config"
+
+	# Just move it. Why using sed?
+	mv $pkgdir/usr/doc/llvm-${pkgver} $pkgdir/usr/doc/clang-${pkgver} 
+
+	# Install html docs
+	cp -r docs/_build/html/* "$pkgdir/usr/doc/$pkgname-${pkgver}/html/"
+	rm -r "$pkgdir/usr/doc/$pkgname-${pkgver}/html/_sources"
+	install -Dm644 LICENSE.TXT "$pkgdir/usr/share/licenses/clang/LICENSE"
 }
+
 
 clang_analyzer() {
 	pkgname=clang-analyzer
@@ -175,8 +206,9 @@ clang_analyzer() {
 	adddep="clang=${pkgver}"
 }
 
+
 clang_analyzer_prep() {
-	cd "$srcdir/llvm-$pkgver/tools/clang"
+	cd "$srcdir/llvm-$pkgver.src/tools/clang"
 
 	install -d "$pkgdir"/usr/{bin,lib${LIBDIRSUFFIX}/clang-analyzer}
 	for _tool in scan-{build,view}; do
@@ -184,8 +216,18 @@ clang_analyzer_prep() {
 		ln -s /usr/lib${LIBDIRSUFFIX}/clang-analyzer/$_tool/$_tool "$pkgdir/usr/bin/"
 	done
 
+	# scan-build looks for clang within the same directory
+	ln -s /usr/bin/clang "$pkgdir/usr/lib${LIBDIRSUFFIX}/clang-analyzer/scan-build/"
+
+	# Relocate man page
+	install -d "$pkgdir/usr/man/man1"
+	mv "$pkgdir/usr/lib/clang-analyzer/scan-build/scan-build.1" \
+	    "$pkgdir/usr/man/man1/"
+
 	# Compile Python scripts
 	python -m compileall "$pkgdir/usr/lib${LIBDIRSUFFIX}/clang-analyzer"
 	python -O -m compileall "$pkgdir/usr/lib${LIBDIRSUFFIX}/clang-analyzer"
+
+	install -Dm644 LICENSE.TXT "$pkgdir/usr/share/licenses/clang-analyzer/LICENSE"
 }
 
