mpd 0.18.10-1 i686 by SirAnthony

diff --git a/mpd/files/mpd.init b/mpd/files/mpd.init
--- a/mpd/files/mpd.init
+++ b/mpd/files/mpd.init
@@ -1,7 +1,7 @@
 #!/sbin/runscript
-# Copyright 1999-2013 Gentoo Foundation
+# Copyright 1999-2014 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/media-sound/mpd/files/mpd.init,v 1.3 2013/07/02 14:24:32 jer Exp $
+# $Header: /var/cvsroot/gentoo-x86/media-sound/mpd/files/mpd2.init,v 1.1 2014/04/15 16:35:25 angelos Exp $
 
 depend() {
 	need localmount
@@ -14,6 +14,11 @@ checkconfig() {
 		return 1
 	fi
 
+	if ! grep -q ^pid_file /etc/mpd.conf; then
+		eerror "Invalid configuration: pid_file needs to be set."
+		return 1
+	fi
+
 	return 0
 }
 
@@ -21,12 +26,12 @@ start() {
 	checkconfig || return 1
 
 	ebegin "Starting Music Player Daemon"
-	start-stop-daemon --start --quiet --background --exec /usr/bin/mpd --pidfile /var/run/mpd.pid --make-pidfile -- --no-daemon /etc/mpd.conf 2>/dev/null
+	start-stop-daemon --start --quiet --exec /usr/bin/mpd -- /etc/mpd.conf 2>/dev/null
 	eend $?
 }
 
 stop() {
 	ebegin "Stopping Music Player Daemon"
-	start-stop-daemon --stop --exec /usr/bin/mpd --pidfile /var/run/mpd.pid
+	/usr/bin/mpd --kill
 	eend $?
 }
