vim 7.4.5-1 i686 by SirAnthony

diff --git a/vim/ABUILD b/vim/ABUILD
--- a/vim/ABUILD
+++ b/vim/ABUILD
@@ -1,9 +1,9 @@
 # ABUILD generated by mkpkg_generator.sh
 
 pkgname=vim
-_basever=7.3
-_srcver=73
-pkgver=7.3.1214
+_basever=7.4
+_srcver=74
+pkgver=7.4.5
 pkgbuild=1
 arch=('auto')
 
@@ -16,7 +16,7 @@ CTAGSVER=5.8
 source=("ftp://ftp.vim.org/pub/vim/unix/vim-${_basever}.tar.bz2"
 "http://citylan.dl.sourceforge.net/project/ctags/ctags/$CTAGSVER/ctags-$CTAGSVER.tar.gz")
 
-build_deps='acl attr gpm glibc-solibs lftp rsync python'
+build_deps='acl attr gpm glibc-solibs lftp rsync python perl'
 
 PYVER=$(python -V 2>&1 | cut -f 2 -d' ' | cut -f 1-2 -d.)
 
@@ -34,10 +34,14 @@ config_vim() {
 		--enable-multibyte \
 		--enable-cscope \
 		--with-features=huge \
+		--enable-acl \
+		--enable-gpm \
+		--enable-perlinterp \
+		--disable-rubyinterp \
+		--disable-python3interp \
+		--disable-luainterp \
+		--disable-netbeans \
 		--with-compiledby="AgiliaLinux"
-
-	# I had been adding this, but got 100% complaints and 0% kudos:
-	#  --enable-rubyinterp
 }
 
 build() {
@@ -46,8 +50,7 @@ build() {
 	# Build CTAGS
 	cd $srcdir/ctags-$CTAGSVER
 	chown -R root:root .
-	find . \
-		\( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
+	find . \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 		-exec chmod 755 {} \; -o \
 		\( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 		-exec chmod 644 {} \;
@@ -59,6 +62,15 @@ build() {
 	install -Dm0644 ctags.1 $pkgdir/usr/man/man1/ctags.1
 	
 	cd ${srcdir}/vim${_srcver}
+
+	# Read vimrc and gvimrc from /etc/vim
+	sed -i 's|^.*\(#define SYS_.*VIMRC_FILE.*"\) .*$|\1|' src/feature.h
+	sed -i 's|^.*\(#define VIMRC_FILE.*"\) .*$|\1|' src/feature.h
+
+	# Don't be fooled by /usr/include/libc.h. When found, vim thinks
+	# this is NeXT, but it's actually just a file in dev-libs/9libs
+	# This fixes bug 43885 (20 Mar 2004 agriffis)
+	sed -i 's/ libc\.h / /' src/configure.in || die 'sed failed'
 
 	# If there's no syntax update, create one:
 	rm -rf runtime/syntax.orig
@@ -79,17 +91,18 @@ build() {
 
 	burn_patches
 
+	(cd src && autoconf)
+
 	# Configure vim. For gvim, there will be little other options
 	config_vim --without-x --disable-gui
 	make -j${numjobs} || make
 	make install DESTDIR=$pkgdir
-
 }
 
 
 after_build() {
 	cd ${srcdir}/vim${_srcver}
-	
+
 	rsync -lprvt $pkgdir/usr/share/man/ $pkgdir/usr/man/
 	rm -r $pkgdir/usr/share/man
 
@@ -117,17 +130,9 @@ after_build() {
 	fi
 
 	# Legacy binary links:
-	( cd $pkgdir/usr/bin ; rm -rf ex )
-	( cd $pkgdir/usr/bin ; ln -sf vim ex )
-	( cd $pkgdir/usr/bin ; rm -rf rview )
-	( cd $pkgdir/usr/bin ; ln -sf vim rview )
-	( cd $pkgdir/usr/bin ; rm -rf rvim )
-	( cd $pkgdir/usr/bin ; ln -sf vim rvim )
-	( cd $pkgdir/usr/bin ; rm -rf view )
-	( cd $pkgdir/usr/bin ; ln -sf vim view )
-	( cd $pkgdir/usr/bin ; rm -rf eview )
-	( cd $pkgdir/usr/bin ; ln -sf vim eview )
-	( cd $pkgdir/usr/bin ; rm -rf evim )
-	( cd $pkgdir/usr/bin ; ln -sf vim evim )
+	for bin in ex rview rvim view eview evim ; do
+	  ( cd $pkgdir/usr/bin ; rm -rf $bin )
+	  ( cd $pkgdir/usr/bin ; ln -sf vim $bin )
+	done
 }
 
