udev 206-1 i686 by SirAnthony

diff --git a/udev/files/gentoo-scripts/init.d/udev-mount b/udev/files/gentoo-scripts/init.d/udev-mount
--- a/udev/files/gentoo-scripts/init.d/udev-mount
+++ b/udev/files/gentoo-scripts/init.d/udev-mount
@@ -1,11 +1,12 @@
 #!/sbin/runscript
-# Copyright 1999-2010 Gentoo Foundation
+# Copyright 1999-2013 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 description="mount devtmpfs on /dev"
 
 depend()
 {
+	provide dev-mount
 	keyword -vserver -lxc
 }
 
@@ -14,9 +15,14 @@ mount_dev_directory()
 	local mounted=false fstab=false action=--mount msg=Mounting rc=0
 
 	if ! grep -qs devtmpfs /proc/filesystems; then
-		eerror "Udev uses a devtmpfs mounted on /dev to manage devices."
-		eerror "This means that CONFIG_DEVTMPFS=y is required"
-		eerror "in the kernel configuration."
+		eerror "CONFIG_DEVTMPFS=y is required in your kernel configuration"
+		eerror "for this version of udev to run successfully."
+		eerror "This requires immediate attention."
+		if ! mountinfo -q /dev; then
+			mount -n -t tmpfs dev /dev
+			busybox mdev -s
+			mkdir /dev/pts
+		fi
 		return 1
 	fi
 
@@ -57,28 +63,18 @@ seed_dev()
 	# udevd will dup its stdin/stdout/stderr to /dev/null
 	# and we do not want a file which gets buffered in ram
 	[ -c /dev/null ] || mknod -m 666 /dev/null c 1 3
-	${HAVE_SELINUX} && restorecon /dev/null
 
 	# so udev can add its start-message to dmesg
 	[ -c /dev/kmsg ] || mknod -m 660 /dev/kmsg c 1 11
 
 	# Create problematic directories
 	mkdir -p /dev/pts /dev/shm
-	${HAVE_SELINUX} && restorecon -R /dev >/dev/null
 	return 0
 }
 
 start()
 {
 	mount_dev_directory || return 1
-
-	# Selinux lovin; /selinux should be mounted by selinux-patched init
-	if [ -x /sbin/restorecon -a -c /selinux/null ]; then
-		HAVE_SELINUX=true
-		restorecon /dev > /selinux/null
-	else
-		HAVE_SELINUX=false
-	fi
 
 	seed_dev
 	return 0
